all:
	gcc -Wall -o main.o main.c
	gcc -Wall -o main1.o main1.c
	gcc -Wall -o main2.o main2.c
	gcc -Wall -o main3.o main3.c
	gcc -Wall -o main4.o main4.c
	gcc -Wall -o main5.o main5.c
	gcc -Wall -o main6.o main6.c
	gcc -Wall -o main7.o main7.c
	gcc -Wall -o main8.o main8.c
	gcc -Wall -o main9.o main9.c
	gcc -Wall -o main10.o main10.c
	gcc -Wall -o h1.o h1.c
	gcc -Wall -o h2.o h2.c
	gcc -Wall -o h3.o h3.c
clean:
	rm -rf *.o
